"""card domain tables

Revision ID: eebe2dde98ac
Revises: c80d3b038d1b
Create Date: 2026-08-26 15:28:58.004105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eebe2dde98ac'
down_revision: Union[str, Sequence[str], None] = 'c80d3b038d1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('title_definition',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=10), nullable=False),
    sa.Column('sport_code', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('player_card',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('public_slug', sa.String(length=80), nullable=False),
    sa.Column('og_image_key', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_slug', name='uq_player_card_slug'),
    sa.UniqueConstraint('user_id', name='uq_player_card_user')
    )
    op.create_table('user_title',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title_code', sa.String(length=40), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['title_code'], ['title_definition.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'title_code', name='uq_user_title_user_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_title')
    op.drop_table('player_card')
    op.drop_table('title_definition')
    # ### end Alembic commands ###
