"""분석 리포트 적재 자리 — analysis_metric_criterion 신설 + report/metric 컬럼

Revision ID: efcf961d0051
Revises: ee536b0b454c
Create Date: 2026-09-10

미결 `jin` 27번. 워커가 S3 에 올린 `report.json` 을 DB 로 적재하려는데
`result.breakdown[]` 의 항목별 맥락(칭호·구간·근거 문장)을 담을 자리가 없었다.
필드 목록의 정본은 `agent/contracts/report_schema.yaml` 의 `breakdown_item`·
`skipped_item` 이고, (b) 안(JSON 블롭이 아니라 행 테이블)으로 확정했다 —
읽기 경로가 「DB 조립 + 허용목록」(계약 3-1)이라 구조가 그대로 남아야 SELECT
컬럼이 곧 허용목록이 된다.

## 무엇을 넣나

- **`analysis_metric_criterion`**: `result.breakdown[]`·`result.skipped[]` 항목당
  1행. `skipped=True` 행은 `grade`·`title`·`evidence` 가 NULL — 없음이 곧 「제외」
  다(0점 아님). `criterion_id` 에 FK 를 걸지 않는다 — 종목·동작 안에서만 유일해
  `grade.{sport}.{motion}.{id}` 로 합성해야 `metric_definition` 에 붙는다.
- **`analysis_metric` +3**: `rubric_sport`·`rubric_motion`·`rubric_version` —
  위 합성에 필요하다. `pipeline_version`(분석 코드)과 다른 축(채점 기준 버전).
- **`analysis_report` +4**: `schema_version`(모르는 major 는 적재가 거부하지만
  실린 값은 판별용으로 남긴다) · `provisional`(검수 전) · `previews`(스켈레톤
  미리보기 URI) · `keypoint_quality`(계약 3장 4 「신뢰도」, `jin` 27번 곁가지).

## 왜 전부 nullable

옛 행(적재 이전 테스트 데이터)에 값이 없다. 새 적재는 이 값을 늘 채운다.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efcf961d0051'
down_revision: Union[str, Sequence[str], None] = 'ee536b0b454c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_metric_criterion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_metric_id', sa.Uuid(), nullable=False),
    sa.Column('criterion_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('grade', sa.SmallInteger(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('contribution', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('band', sa.String(length=60), nullable=True),
    sa.Column('out_of_band', sa.String(length=40), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('metric_ref', sa.String(length=50), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_metric_id'], ['analysis_metric.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_metric_id', 'criterion_id', name='uq_metric_criterion_item')
    )
    op.add_column('analysis_metric', sa.Column('rubric_sport', sa.String(length=20), nullable=True))
    op.add_column('analysis_metric', sa.Column('rubric_motion', sa.String(length=30), nullable=True))
    op.add_column('analysis_metric', sa.Column('rubric_version', sa.String(length=20), nullable=True))
    op.add_column('analysis_report', sa.Column('schema_version', sa.String(length=10), nullable=True))
    op.add_column('analysis_report', sa.Column('provisional', sa.Boolean(), nullable=True))
    op.add_column('analysis_report', sa.Column('previews', sa.JSON(), nullable=True))
    op.add_column('analysis_report', sa.Column('keypoint_quality', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_report', 'keypoint_quality')
    op.drop_column('analysis_report', 'previews')
    op.drop_column('analysis_report', 'provisional')
    op.drop_column('analysis_report', 'schema_version')
    op.drop_column('analysis_metric', 'rubric_version')
    op.drop_column('analysis_metric', 'rubric_motion')
    op.drop_column('analysis_metric', 'rubric_sport')
    op.drop_table('analysis_metric_criterion')
    # ### end Alembic commands ###
