"""analysis domain tables

Revision ID: ebc1eeecd54d
Revises: eebe2dde98ac
Create Date: 2026-08-28 15:19:51.037972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebc1eeecd54d'
down_revision: Union[str, Sequence[str], None] = 'eebe2dde98ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_definition',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('sport_code', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('video',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('sport_code', sa.String(length=20), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('side', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('video_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_metric',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_job_id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_job_id'], ['analysis_job.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_job_id', name='uq_analysis_metric_job')
    )
    op.create_table('analysis_metric_value',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_metric_id', sa.Uuid(), nullable=False),
    sa.Column('metric_code', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('frame_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_metric_id'], ['analysis_metric.id'], ),
    sa.ForeignKeyConstraint(['metric_code'], ['metric_definition.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_metric_id', 'metric_code', name='uq_metric_value_item')
    )
    op.create_table('analysis_report',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_metric_id', sa.Uuid(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_metric_id'], ['analysis_metric.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_metric_id', name='uq_analysis_report_metric')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_report')
    op.drop_table('analysis_metric_value')
    op.drop_table('analysis_metric')
    op.drop_table('analysis_job')
    op.drop_table('video')
    op.drop_table('metric_definition')
    # ### end Alembic commands ###
